[features]
seeds = false
skip-lint = false
[programs.devnet]
mint_nft = "HF6Xskjab5hNuYDbyySMi2o9zr5w5mGoE7Pqh3fdWDvQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/atulpal/my-solana-wallet/keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
